# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriessecond',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.CategoriesFirst'),
            preserve_default=False,
        ),
    ]
