# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categoriessecond_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.CategoriesSecond'),
            preserve_default=False,
        ),
    ]
