# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.CharField(max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.AlterField(
            model_name='categoriessecond',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand'),
            preserve_default=False,
        ),
    ]
