# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170626_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(blank=True, default=0, verbose_name='Просмотры'),
        ),
    ]
