# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('two_name', models.CharField(max_length=256, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('stat', models.CharField(max_length=256, verbose_name='Город')),
                ('street', models.CharField(max_length=256, verbose_name='Улица')),
                ('house', models.CharField(max_length=256, verbose_name='Дом')),
                ('index', models.CharField(max_length=256, verbose_name='Индекс')),
                ('att', models.TextField(verbose_name='Примечания')),
                ('product', models.TextField(verbose_name='Товары')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
